### ISSUE TITLE
`cundefined` classname

### ISSUE THREAD

**Issue by sompylasar** [sandhose/prettier-animated-logo#1]
<img width="606" alt="screen shot 2018-01-12 at 5 18 35 pm" src="https://user-images.githubusercontent.com/498274/34901246-a8f125de-f7bc-11e7-8726-801df8edac02.png">

**Comment by sandhose** [comment]
It's because the way I define colors is [kinda simple](https://github.com/sandhose/prettier-animated-logo/blob/8e13a27faf8a44d1f8769b38017ed1526f87adf9/index.js#L12), and if a dash has no color defined in the [`data.json`](https://github.com/sandhose/prettier-animated-logo/blob/8e13a27faf8a44d1f8769b38017ed1526f87adf9/data.json), `color` will be `undefined`. Not a big deal though, I can certainly do something to get rid of this class.

**Comment by sandhose** [comment]
Now there's a `.c0` class on the gray dashes, with proper opacity and color styles.
